# Generated by Django 4.1.7 on 2023-03-05 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField()),
                ('job_description', models.TextField()),
                ('is_published', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('birth_date', models.DateField()),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('bio', models.TextField()),
                ('is_active', models.BooleanField()),
                ('shift_start_at', models.DateField()),
                ('shift_ends_at', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_app.department')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee_app.job_application')),
            ],
        ),
    ]
