# Generated by Django 4.1.7 on 2023-03-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_rename_department_job_application_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application',
            old_name='name',
            new_name='department',
        ),
    ]
