# Generated by Django 3.2 on 2023-03-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_alter_employee_applicant_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_applicant',
            name='prefix',
        ),
        migrations.AddField(
            model_name='employee_applicant',
            name='job_application',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(is_published='True'), null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_app.job_application'),
        ),
    ]
