# Generated by Django 3.2 on 2023-03-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_auto_20230312_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_applicant',
            name='employee_bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee_applicant',
            name='employee_full_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee_applicant',
            name='status',
            field=models.CharField(choices=[('available', 'Available to borrow'), ('borrowed', 'Borrowed by someone'), ('pending', 'pending - not accepted yet')], default='pending', max_length=15),
        ),
    ]
