# Generated by Django 3.2 on 2023-03-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_auto_20230312_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_applicant',
            name='employee_bio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='employee_applicant',
            name='employee_full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_applicant',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('pending', 'pending')], default='pending', max_length=15),
        ),
    ]
