# Generated by Django 3.2 on 2023-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_auto_20230312_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift_start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
