# Generated by Django 4.1.7 on 2023-03-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0009_auto_20230312_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('pending', 'pending')], default='pending', max_length=15, null=True),
        ),
    ]
