# Generated by Django 4.1.7 on 2023-03-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0011_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
